/* Reezer dashboard — user-facing product version + changelog.
   CONVENTION: the version is PER DAY. The first dashboard change on a new day bumps
   NT_VERSION by +0.001 and adds a new {v, date, notes:[]} entry at the TOP of
   NT_CHANGELOG (newest first); further changes the SAME day just append a bullet to
   that day's `notes` (version unchanged). Separate from the ?v= asset cache-buster. */
window.NT_VERSION = "1.026";

window.NT_CHANGELOG = [
  {
    v: "1.026", date: "2026-08-22",
    notes: [
      "Crypto \u00b7 BETA is now a world of its own in the menu \u2014 dashboard, trades, alerts and strategies, all reading their own tables, all marked BETA so an empty page reads as \u201cnot built yet\u201d rather than \u201cbroken\u201d. It also takes part in the top bar: the run-state panel lists it with its own stop control, the positions panel will show crypto holdings, and the sessions panel shows Revolut X as open 24/7. One paper strategy exists, Revolut X beta (paper); nothing trades yet.",
      "Settings \u2192 Brokers now lists the newest broker first: Revolut X, then Interactive Brokers, then Charles Schwab.",
      "A fourth world is on its way, in beta: crypto on Revolut X. The first visible piece is the broker itself \u2014 Revolut X now appears in Settings \u2192 Brokers, marked crypto \u00b7 beta, with the account value and balances Reezer reads from the venue each day, the same way the IBKR and Schwab rows work. No crypto trading happens yet; the signal sheet and the strategies come next.",
      "The separate Resting orders card is gone: an order on its way \u2014 queued for the open, or resting at IBKR \u2014 now appears as an amber row inside Your portfolio, and turns into a normal position row when it fills. The card's count includes them.",
      "A buy or sell the engine is holding for the next market open now shows on the swings dashboard as a queued order, in amber, next to the resting orders. The engine deliberately waits when the market is closed \u2014 with no price to check the contract against, ordering blind would drop a safety guard \u2014 but that waiting used to be invisible, which read as nothing happening.",
      "Servers can now update themselves: an Update code button per server pulls the latest code from a private repository and restarts that server's jobs \u2014 no more walking to the machine, running Connect and remembering to restart. Each server also shows the exact code version it is running next to its name, so \u201cis the fix live on that box?\u201d is answered by looking. An update is refused while a server is actively trading, enforcing the no-deploys-mid-session rule by software.",
      "The top bar now speaks for all three worlds. The LIVE badge opens a run-state panel: each world's LIVE/PAPER state, how recently it reported, and a stop control per world \u2014 options kills and closes, swings and futures block new orders (open positions stay). The strategies pill is replaced by open positions across every world, each in its own currency, one click from its trades page. The session clock shows each world's market hours plus its watching window from Settings \u2014 \u201cStreaming\u201d jargon is gone \u2014 and the badge counts how many of your markets are open right now.",
      "Table row lines across every page \u2014 options trades and alerts, activity, settings, Exit Lab, swings \u2014 are now slightly dimmer so they read the same as the card frame (the same colour looks brighter inside a card than at its edge), and the row hover highlight is softer everywhere.",
      "The Macrotrends page now has two tabs: his current portfolio (the default) and his closed positions \u2014 the sell log Reezer already watches for exit signals, all 42 of his past exits with entry, exit and result. Sorting of the open tab now counts only real decisions \u2014 an advice change, a weight change or a new addition.",
      "The publisher's portfolio has its own page now: Macrotrends, in the swings menu. On the alerts feed it vanished as soon as alerts piled up; as a page the table is always open, sorted by his latest real change. A violet dot marks every stock you hold from his book, the card header counts them, and the \u201cyour p&l\u201d column shows your own percentage \u2014 broker-priced while you hold, the realized figure once sold.",
      "Fixed: the Alerts page said \u201clagging\u201d while everything was healthy. The badge measured the age of the last sheet change \u2014 but a change is only recorded when the publisher actually edits something, so a quiet sheet looked like a broken feed. It now measures when Reezer last checked the sheet (every ~5 minutes), and shows the last change separately.",
      "The P&L card now leads with your total profit \u2014 realized and unrealized together \u2014 with the split spelled out underneath. Win rate is replaced by Invested: what share of your account is actually at work, a more telling number for a book of long holds than the hit rate of a handful of exits. The same cards now sit on the Trades page too, and its percentage pills match the status pills in size.",
      "The swings Trades page now uses the same table as Your portfolio \u2014 same columns, same layout \u2014 with a status column since closed positions live here too, P&L instead of unrealized P&L, and an All / Open / Closed filter. A closed position is priced at its exit; an open one at IBKR's current value. The dates a position ran are shown under the company name.",
      "Fixed: the S&P comparison read 0.0% \u2014 as if it were missing \u2014 because it measured the index from the close of your first buy day instead of the close before it, so the buy day's own move never counted. It now measures from 20 August's close, updates with every daily close, and from 1 January it automatically becomes an ordinary calendar-year comparison.",
      "Trades page totals are now in your account's currency \u2014 euros, matching IBKR \u2014 instead of dollars. \u201cYou could buy now\u201d drops a stock the moment you own it. Portfolio columns reordered (company, shares, capital, buy-in, current price, market value, profit, %) and evenly spaced. Industry tags are plain text.",
      "Swings dashboard: Holdings is now called Your portfolio, with the IBKR sync stamp up in its header. A new Capital column shows what each position cost including commission, next to what it is worth now, and the profit percentage is much bigger. Return this year and the S&P comparison both measure your invested capital \u2014 open and closed positions over what they cost \u2014 rather than the whole account.",
      "Swings alerts: the statistics bar moved to the Trades page where it belongs. Alert badges are now simply BUY, HOLD or SELL \u2014 the from\u2192to detail already lives in the advice column. The industry tag has its own column title and no longer fades into the background. The Macrotrends portfolio table folds open and closed, its columns read Current price and Result, and it is sorted by the publisher's last real change to each name \u2014 price moves don't count, or the whole table would reshuffle daily.",
      "The three settings cards \u2014 Dashboard, Brokers, Alert sources \u2014 now always share the same height, matching the tallest of the row.",
      "The menu is a little wider, and the world switcher is now the same height as the Ask Reezer button, so the selected item, the switcher and the button all line up.",
      "Settings starts with the choice that frames everything else: which world your dashboard opens on. Below it you can now set a default strategy per world \u2014 each world keeps its own choice, so picking a futures strategy no longer quietly becomes the options default too.",
      "Interactive Brokers is listed first among the brokers, the page stretches to use the full width of the window, and the New source button \u2014 which did nothing \u2014 is gone.",
      "Your Macs are now called servers everywhere \u2014 no more \u201cboxes\u201d or \u201cmachines\u201d.",
    ],
  },
  {
    v: "1.025", date: "2026-08-21",
    notes: [
      "The S&P comparison now measures your whole portfolio, cash included, rather than only the part of it that happens to be invested. The index return assumes you were fully invested in it, so comparing it against deployed capital alone flattered the strategy by hiding the money it chose to leave in cash. Both figures are shown \u2014 portfolio and invested \u2014 so the cash drag is visible instead of hidden.",
      "Fixed: the same position showed -0.1% in the holdings table and -0.7% on the S&P card. Two separate pieces of code were working out the same profit in two different ways, and one of them was dividing a converted amount by an unconverted one. Every percentage on the page now comes from one figure: IBKR's profit for the position, over what you paid for it.",
      "Your profit and loss is now IBKR's own figure, asked for directly, instead of something calculated here from a price. A share has several prices at once \u2014 the last trade, the midpoint, the official close \u2014 and after-hours trading on Tradegate moves one while IBKR keeps valuing at another, so any figure worked out from a price was always going to drift from your broker screen. Now the dashboard shows the same number IBKR does, because it is the same number.",
      "Holdings are valued at the last traded price, the same one IBKR uses. They were briefly valued at the midpoint between the best bid and offer, which is the right price for placing an order but not for valuing something you already own \u2014 it read \u20ac0.44 away from the broker on Zalando.",
      "Live prices now refresh on their own schedule (about every 30 seconds) instead of waiting for the portfolio sheet, which is only re-read every five minutes because Google caches it. Sheet polling itself is unchanged.",
      "Fixed: your SES order expired the same evening instead of waiting for the next session. It was sent as a day order two minutes after Euronext closed, so the exchange dropped it at end of day \u2014 nothing was bought and nothing said it would happen. Swing orders are now good-till-cancelled, and the resting-orders table shows how long each order lives, so an order that will not survive the night is visible rather than implied.",
      "Your profit and loss is now priced from IBKR, not from the publisher's spreadsheet. His sheet kept revising prices long after the exchange closed \u2014 Zalando wandered from 22.58 to 22.70 to 22.78 over forty minutes on a shut market \u2014 and your P&L followed it, moving \u20ac2.20 on a position that had not traded. Your purchase price was always your own; it was today's price that came from the wrong place.",
      "Holdings table rebuilt: shares, your buy-in, current price, market value and profit each get their own column, with the percentage beside the amount, and the rows have room to breathe. \u201cValue\u201d used to show what a holding cost rather than what it is worth \u2014 it now shows market value.",
      "Fixed: the \u201cvs S&P 500\u201d card was blank on the day of your first trade. It measured the index from your first buy but needed an index price dated that same day, which does not exist until the session closes. It now takes the last close before you bought, so the comparison works from day one. Its return figure was also mixing dollars and euros, reading -1.3% where the truth was -1.1%.",
      "Position sizes are now set in your account's own currency. Your IBKR account is in euros, but sizing was computed in dollars, so a tier of 300 bought about \u20ac259 of stock instead of \u20ac300 \u2014 roughly 16% short on every position. A 2% weight now buys 61 SES instead of 52, and 13 Zalando instead of 11. The existing SES order is left as it was.",
      "Closed a gap that let anyone holding the dashboard's public key read or alter the swing order book. It is now restricted to your signed-in account, matching every other table.",
      "Holdings are now shown in their own currency \u2014 a Zalando position reads in euros, a Toronto one in Canadian dollars \u2014 and the table now shows the price you actually paid, the price it is currently marked at, and the resulting profit to the cent. Converting everything to dollars made the dashboard disagree with the IBKR screen for no good reason. Totals across all holdings are still converted to USD, since four currencies cannot be added up, and the card now says so.",
      "The Macrotrends portfolio table now shows what he paid for each holding next to today's price, so you can see at a glance which names are still available at or below his entry.",
      "Swings now shows Resting orders on the dashboard: an order that has been sent to the broker but has not filled yet. Placing a market order after the exchange closes leaves it waiting at the venue until the next opening auction, and until now nothing on screen told you that your money was already committed.",
      "Swing orders are now plain market orders. The old style priced them just through the offer, which produced a price the exchange refused outright (\u201cthe price does not meet the minimum price variation\u201d) and cost a real buy on 21 August. A market order has no price to get wrong.",
    ],
  },
  {
    v: "1.024", date: "2026-08-20",
    notes: [
      "When you set a stop or target in ticks, the strategy now shows what that is worth in real money for every instrument it trades, including the number of contracts — so 40 ticks reads as \u201c$20 MNQ \u00b7 $50 MES \u00b7 $40 MGC\u201d as you type it, and the same figure appears on the strategy card.",
      "Futures strategies now speak the language of futures: risk is set in ticks instead of percentages (MNQ: 1 tick = 0.25 points = $0.50), and size is a number of contracts instead of a dollar budget — a dollar figure is meaningless when one contract controls tens of thousands of index. A strategy also only offers the alert channels of its own world.",
      "Fixed: new strategies were created but never appeared, so clicking again just made more invisible ones. The strategy list dropped the category when preparing the page, so every world's filter matched nothing. Four empty drafts from that have been cleaned up.",
      "Futures strategies now offer the same three exit choices as options: follow the trader's exits, use only your own rules, or both — whichever comes first. Following the trader means exactly that: no stop, no target, no time limit.",
      "Futures prices are now checked twice a second instead of every ten seconds, matching the options bot, with quotes cached per tick so it doesn't hammer the broker.",
      "Futures now has real Strategies and Trades pages instead of placeholders — the same cards and tables as Options, so the futures strategy is edited the same way, with its own stop, target and maximum hold.",
      "Strategies are now shown per world. Before, every strategy lived in one list, so the futures strategy could appear among the options ones; each world now shows only its own, and a strategy created from a world belongs to it.",
      "Fixed: profit on a futures trade was calculated as if it were an option (100 per contract). Each futures contract now uses its own value per point — 2 for MNQ, 5 for MES, 10 for gold — so open positions and exit prices read correctly.",
      "Recovered the trade history: every strategy shows its full record from June again, the duplicated June trades in No Stop strategy are removed, and the missing July weeks were replayed for both paper strategies. Bulk deletion of trade history is now blocked at the database, and a copy of all positions is saved automatically every night.",
    ],
  },
  {
    v: "1.023", date: "2026-08-18",
    notes: [
      "Fixed: futures alerts were appearing in the options alert list. All alerts share one table, and the feed was not filtered by world — so each world now shows only its own, including the fired/filtered counts.",
      "Futures is now a third world in Reezer, reading the futures Discord channel. Only PT | Nitro Trades is recorded — the other people posting in that channel are never stored at all, so the alert feed is his calls and nothing else. Each alert shows the instrument (MNQ, MES, MGC…) and, for an entry, the direction, plus a plain-language note when a message was read but deliberately not acted on. Nothing is traded yet: this reads and records only.",
      "The futures dashboard is now the same page as the options one — same six headline cards, same trades table, same chart, same alert feed — just scoped to futures. Most of it is empty until it trades, which is deliberate: the page should not change shape when data starts arriving.",
      "Because there are now three worlds, the Options / Swings switch became a picker at the top of the menu. Each world shows its own state next to its name — how many strategies are live, how many alerts came in — so the menu tells you where to look, not just where you are. With only one world it stays hidden, exactly as before.",
      "Swings now uses the same LIVE badge as Options — green with a pulsing dot. It was red before, which read as an error when the strategy was simply armed and working.",
      "Large numbers no longer use a thousands separator anywhere, so $1100 reads as $1100 instead of $1.100 (which looked like a decimal).",
      "Settings fills the page properly on a wide screen: Dashboard, Brokers and Alert sources now sit side by side, with Machines full width beneath since it is a real table. Two columns on a laptop, one on a narrow window.",
      "Both broker accounts refresh themselves every 15 minutes between 10:00 and 22:00, so the account value on the dashboard matches what your broker shows instead of being yesterday's figure. Outside those hours nothing changes at a broker, so it does not poll.",
    ],
  },
  {
    v: "1.022", date: "2026-08-17",
    notes: [
      "Both broker rows in Settings are now built the same way: name, masked account number, live account value, and when it was last checked. Schwab's balance is synced from the broker each morning just like IBKR's, and a broker that hasn't reported for over a day says STALE instead of pretending it's linked. A cloud watchdog was also added for the swing world: if the morning health check doesn't report by 09:30, your phone gets an alarm — even when the Mac itself is asleep, because the watchdog runs in the cloud, not on the Mac.",
      "Fixed: the Settings page went blank — a one-letter typo in the alert-sources list crashed the whole page while the sources were being drawn. Also removed a duplicated “return this year” card on the Swings dashboard.",
      "A swing strategy can now actually go live: the editor has a Paper / Live switch (with a clear warning — live places real orders with your money once the strategy is unpaused), and a “bid above the offer” setting that controls how aggressively an order is priced so it fills right away. There is deliberately no skip-if-the-price-rose rule anymore: these are positions held for months, so the trade is always taken — the only price check left is a broken-price guard against wrong contracts or currencies.",
      "Orders that don't fill immediately are no longer forgotten. Every real order is written down the moment it's sent; one that rests overnight (normal for an alert that arrives after the market closes) is checked every few minutes and, when it fills, the position appears by itself at the real fill price with a push message. If the publisher exits a position while our entry is still waiting, the entry is cancelled instead of buying into a position that no longer exists. Sizing also now converts currencies properly — a Canadian or European holding is bought for the intended dollar amount, not a mis-converted one.",
      "Settings is tidier. Alert sources are now a clean list — one line per source with its address, when it runs, and whether it's on — grouped under a quiet heading per category instead of a cramped table. The separate “Streaming window” box is gone: a source's hours now live on the source itself, so each one can keep its own schedule (a channel that posts at the open, another midday), and a source with no hours simply runs all day. Brokers got the same treatment, with Interactive Brokers listed and ready to connect.",
      "Swing positions are now sized by conviction. The sheet grades every holding 1%, 2% or 3%, and you decide what each of those is worth to you — either a fixed amount per position, or a percentage of your account. Four rows (1%, 2%, 3%, above 3%) and nothing else: no notional, no pot, and no account size to type in, because your account value comes from your broker. Setting it lives on the strategy itself, where it belongs.",
      "Your swing profit now includes positions you're still holding. Before, only closed trades counted — so a holding could be up 40% and the dashboard would show nothing until you sold, which for positions held over months meant an empty page most of the year. Open positions are now valued against the sheet's own prices. Everything is shown in US dollars: the portfolio holds euro, pound and Canadian listings, and the exchange rates refresh by themselves every day.",
      "The S&P 500 comparison only counts once you've actually bought something, and in your first year it measures from your first purchase rather than from January — comparing a strategy that started in August against the index's whole year would have shown a large loss you never took. From next year it becomes a normal year-to-date comparison on its own.",
      "The Activity page now shows what the swing side is doing (it was silent before) and you can filter by category — Options or Swings, with the buttons appearing on their own as new categories are added. Every entry is tagged so you can tell at a glance which world it came from.",
      "Settings is reorganised around the same idea. Alert sources are now one list grouped by category instead of separate places, each with its own schedule; the trading window moved in with Options and is named for it, since it only ever described the Discord session. Brokers and machines stay shared — you connect a broker once and any strategy can use it. And you can now choose which page each world opens on, saved to your account so it follows you between computers.",
    ],
  },
  {
    v: "1.021", date: "2026-08-16",
    notes: [
      "Reezer now has a second world: Swings — long-term positions that follow the Macrotrends portfolio sheet, completely separate from the 0DTE options bot. It has its own Dashboard, Trades, Alerts and Strategies, laid out the same way as the options side so there's nothing new to learn, and an Options / Swings switch appears at the top of the menu as soon as you have both (with only one, there's nothing to switch, so it stays hidden). Exit Lab stays with options only — replaying a day's price tape means nothing for a position you hold for months.",
      "How Swings works: it reads both tabs of the sheet — the holdings tab for buys, the closed-positions tab for sells — and you set what a sheet weight is actually worth to you, either a fixed amount (a 3% holding out of $20,000 = $600) or a share of your account, with an optional per-position cap and ticker filter. It starts flat: nothing is bought up front, it only acts when the publisher changes something, and it can only ever sell what it bought itself — so an exit in a name you never owned is quietly ignored. Physical metal (gold, silver, platinum) is tracked but never ordered. New strategies start paused and on paper; nothing is ordered until you activate one and link a broker.",
      "The Swings dashboard opens with six headline numbers: account return, return this year, net profit, win rate, average return per trade (with how long you hold on average) and how you're doing against the S&P 500. That last one only compares the money actually invested, and shows nothing at all until you've made a trade — otherwise sitting in cash would look like a large loss against a rising market when you simply hadn't started. Alerts lists every change the publisher makes, with a live / lagging / stale badge for how recently the sheet was checked, and greys out anything that's only tracked and never ordered. Your boxes, brokers and sources stay shared in Settings, which is also where you switch swing trading on.",
    ],
  },
  {
    v: "1.020", date: "2026-08-14",
    notes: [
      "Reezer's backtests can now scope to a date window (“…in the past 14 days”, “this week”, a specific range) instead of only full history, and the result card now shows the strategy's real sizing (trade budget + max contracts) rather than a fixed 1 contract.",
      "Ask Reezer can now run REAL backtests. Ask something like “what does a 40% stop do to the No Stop strategy?” and instead of saying it can't, Reezer replays every one of that strategy's recorded trades on the real 1-second tapes with the change applied, answers with the actual numbers, and shows the result in the same strategy overview card (Total P&L · Win Rate · Profit Factor · Avg/Trade · Max Drawdown). It can compare several settings in one go to find the best stop/target.",
      "Ask Reezer now opens scrolled to your most recent message instead of the top — no more scrolling down every time you come back to the chat.",
      "New paper strategies now come fully set up out of the box: they start with a $2,000 notional balance (so the “account return” % shows from day one instead of a blank “—”), and they’re automatically backfilled with your entire trade history — every past alert replayed under that new strategy’s own settings — so a strategy you add today immediately has the full track record to compare against the others. (Your real recorded strategies, Gianni’s and Nitro’s, are left untouched.) The account-return card now also fills in for the existing paper strategies and the live account.",
    ],
  },
  {
    v: "1.019", date: "2026-08-05",
    notes: [
      "Replay is now a proper what-if sandbox. Press Replay on a paper strategy and a panel opens with that strategy's own settings pre-filled — stop, take-profit, take-half, breakeven, max-hold, exit mode, budget, max contracts. With nothing changed it reproduces the strategy's recorded numbers exactly, trade for trade (the same P&L as the card). Change any field and press \"Run what-if\" to see the impact on every recorded trade — and the strategy and its recorded trades are NEVER touched. So you can test ideas without ever editing (and drifting) the real strategy.",
      "Fixed the long-standing Replay drift: its baseline is now the strategy's own recorded trades (all of them), so opening Replay always matches the card. Previously it rebuilt the list from scratch and re-sized to the current budget, so it could silently drop trades and show a different total than the card.",
      "All four paper strategies now carry their full trade history (the \"No Stop with TP\" strategy was only partly filled), each trade's profit computed from that strategy's own settings — and it re-runs automatically every day so new trades fold in on their own.",
      "Fixed \"Max trades / day\" showing a confusing \"0\" instead of empty. 0 and empty both mean \"no daily cap\" (and always did — the bot never limited on 0), so the field now shows blank in that case, and saving/duplicating a strategy stores it as empty rather than 0.",
    ],
  },
  {
    v: "1.018", date: "2026-08-03",
    notes: [
      "Fixed the Trades list jumping around during a live trade — the open row(s) now stay put as the P&L ticks and on the background refresh. Rows are keyed by trade and held in a stable newest-first order, so near-simultaneous entries (several strategies on the same alert) no longer shuffle.",
    ],
  },
  {
    v: "1.017", date: "2026-07-31",
    notes: [
      "Exit Lab: moved the “realized %” column to sit right after “p&l”, so “realized %” and “peak %” are now side by side — easier to compare what a trade actually captured versus its peak, at a glance.",
    ],
  },
  {
    v: "1.016", date: "2026-07-30",
    notes: [
      "Fixed a misleading banner: a successful live order (like a take-profit close for a profit) was showing in the same red “Review needed” alarm as an actual problem. Completed orders now show as a calm, neutral “Live order” notice — only real issues (a rejected order, an unfilled close, a box not ready) stay red. So a green +$82 close no longer looks like something went wrong.",
    ],
  },
  {
    v: "1.015", date: "2026-07-27",
    notes: [
      "New “⚠ Problems only” filter on the Activity page — one tap shows just the warnings and errors (with a count next to it), so you can see what went wrong without scrolling past all the normal activity. Error rows are now tinted red so they stand out even in the full list.",
      "The Activity feed now captures far more of what can go wrong on a live trade, in real time: a strategy choosing NOT to enter (with the exact reason), a Schwab order being rejected or only partly filled, and a box stuck restarting in a loop. Before, several of these were silent — they only ever reached a log file on the box itself, so if you weren’t at that Mac you couldn’t see them. Now they show up on the dashboard (and still page your phone).",
      "Put the Activity page back in the sidebar (Workspace → Activity) — it had been hidden since July, so all the new problem-logging above had nowhere to show. It’s one click from the menu again.",
      "The Activity feed now updates instantly, live — the moment a box logs anything it appears, just like Trades and Alerts (before, it only refreshed on the 10-second background poll).",
    ],
  },
  {
    v: "1.014", date: "2026-07-21",
    notes: [
      "Replay preview: the trade list now scrolls when it's longer than the panel — before, a long list was cut off with no way to reach the rest of the trades (fixed on desktop and touch).",
      "New AI Advisor page — a chat-first assistant that studies every trade you've taken (the full price path to +30 min plus your own Discord feed) and designs a complete strategy from it: trade budget, per-weekday sizing, stops and exits — with the reasoning spelled out and validated on your real trades. Ask it questions right there (\"why no stop?\", \"which day loses money?\") or have it design a fresh one. Your Anthropic key stays in Supabase, never in the browser.",
      "Polished the AI Advisor's orb — a soft glowing, layered sphere with a feathered edge and a breathing halo, instead of the earlier hard-edged circle.",
      "AI Advisor now formats its answers (bold, bullet lists) so they're easy to read instead of showing raw markdown, and a live progress bar with a percentage shows exactly where a strategy design is (loading trades, testing each parameter, Claude designing) so you can see how long is left.",
      "AI Advisor refresh: the button is now \"Analyse my trades\" and first asks which trades to use — all of them, the last 7/30 days, this month, or a custom date range — so you can design a strategy from a chosen window. New organic, animated orb, the background now fades to black under the header and side menu, and the chat input text is vertically centred.",
      "The AI Advisor now has its own standout \"Ask Reezer\" button in the side menu — a gradient pill set apart below the other menu items — instead of a plain nav row.",
      "Ask Reezer upgrades: a proper animated orb; it now asks your date range right in the chat (tap a preset or type a range like 2026-07-01 to 2026-07-15) instead of a pop-up; and it can answer questions about your actual trading — how a day went, a specific trade, or how a strategy did — from your live strategies and trades. Toned down the side-menu button to sit better with the rest.",
      "Ask Reezer now speaks as “Reezer” everywhere (no more “Claude is…”); the strategy write-up comes back as a chat message you can read easily instead of a wall of text in the card; and when it designs a strategy it now also weighs following your Discord alerts and their tone — not just the mechanical rules — so its ideas match how the trades actually played out.",
      "Ask Reezer voice: tap the mic to talk to it, and toggle “Read aloud” to have its replies spoken back.",
      "Ask Reezer is faster and never looks stuck: designing a strategy now runs lighter (about half the wait), the progress bar keeps moving with a live seconds counter while it works, and if the connection ever stalls it times out with a “tap to retry” instead of hanging. Bigger, seamlessly-looping orb that stays visible while you chat; the welcome screen and its glow are now centred; refreshed side-menu orbit icon.",
      "Ask Reezer chat is easier to read: replies are now plain text (no boxes), the strategy write-up is broken into a one-line summary plus short labelled points, and the voice picks the most natural system voice and says it’s thinking before a pause instead of going silent.",
      "Ask Reezer can now speak in a real, natural voice (ElevenLabs) when it’s connected — your voice key stays in Supabase, never in the browser; if it’s not set up it falls back to the built-in system voice.",
      "Hands-free voice conversation: tap the mic once and just talk — Reezer answers aloud and re-opens the mic for you, back and forth, no tapping between turns. It says shorthand as words (“Wed” → Wednesday, “301p” → 301 puts, “20m” → 20 minutes).",
      "Reezer now talks like a person — it greets you by your first name and replies warmly and conversationally instead of like a formal assistant. (Also fixed the voice cutting out.)",
      "Exit Lab no longer lists trades from strategies you've deleted (they used to show up as a nameless “—”). Removed the confusing “Live only” item from the strategy filter — it was a filter, not a real strategy. And the No Stop strategy now has its full trade history in Exit Lab, replayed across every recorded trade, so you can compare it head-to-head with your others.",
      "Voice mode now uses the real (ElevenLabs) voice too — before, only the “Read aloud” toggle did, while hands-free voice fell back to the robotic system voice. And Reezer only says “let me think” when an answer actually takes a moment, not on every quick question.",
      "Reezer now knows its own name is Reezer and won't confuse it with yours. And the No Stop strategy now shows its account return (it was missing a starting balance, so the % had nothing to divide by).",
      "No Stop strategy trades now show their full price path and exit markers when you open one. And Reezer no longer says “let me think” for greetings or quick questions — only for ones that genuinely take a moment.",
      "Fixed the error when switching a strategy to Live — it now automatically links your connected Schwab account (a strategy can’t go live without one), instead of failing to save.",
      "The status dots in the top bar (LIVE, session) now blink in sync instead of drifting apart, and removed the redundant dot on the strategies pill.",
      "Ask Reezer: your conversation is now saved — reload or come back later and it's still there, with a “New chat” button to start fresh. It no longer answers with raw settings code when you ask it for a strategy, and the orb in the chat is much bigger.",
      "Phone alerts now cover every live trade in real time — entries, partials, closes and stop-outs, on top of the existing error alerts. Paper trades stay silent.",
      "Ask Reezer always opens on the clean home screen now, with your previous conversation one tap away under “Continue last chat” — history without the noise. Voice mode also greets you out loud the moment you tap the mic, and if your microphone is blocked it now tells you instead of failing silently.",
      "Ask Reezer now puts the cursor straight in the chat box when you open the page — just start typing, no clicking first. It re-focuses after every reply too.",
      "Your Ask Reezer conversation now follows YOU, not the computer — it's saved to your account, so the same history is there on any Mac or browser you sign in from. And if Claude is momentarily overloaded, it now retries automatically instead of showing you an error.",
      "Strategy analyses are now aimed at ONE goal: the highest total profit. Before, no goal was set, so it could chase a “smoother ride” one time and something else the next — which is why the same question gave two different strategies. It also follows fixed tie-break rules now, so the same trades give you the same answer. Replaced “New chat” (which deleted your history) with a Home button that keeps it, and pressing “Read aloud” now reads the latest reply straight away.",
    ],
  },
  {
    v: "1.013", date: "2026-07-14",
    notes: [
      "Settings → Broker accounts now shows your Schwab connection status at a glance — “expires in X days”, turning amber then red as the ~7-day Schwab login nears expiry, always visible so you can’t miss it.",
      "New “Re-auth Schwab” button right there — no more Terminal: it opens the Schwab login in a new tab, you paste back the URL Schwab redirects you to, and it reconnects. One re-auth covers all your boxes.",
    ],
  },
  {
    v: "1.012", date: "2026-07-01",
    notes: [
      "Date filter now has more presets — Today, This week, Last week, This month, Last month, Year to date, All time — plus Custom range, all in one compact dropdown (replacing the old 3-button toggle, so it takes no extra space on the page).",
      "Fixed the dashboard P&L chart not updating when you change the date range (it was caching the old data).",
      "Strategy cards are tidier — the allowlist is gone from the card and the trailing stop just shows Yes/No (full allowlist + trailing tiers are in the strategy's edit view). The edit form got more breathing room between fields, and the “Exit handling” label now matches the other muted uppercase labels.",
      "Removed the Activity page from the sidebar — it was redundant with Trades + Alerts (the underlying bot-event log still runs for debugging).",
      "Fixed: changing a date picker on a page no longer overwrites your Default date range in Settings. The default is now a separate saved preference — the pages open on it, and a picker only changes your current view for the session.",
      "Trades page: the strategy column now shows each trade’s real strategy name (it was showing “Option” for every row). Widened the hold-time column and fixed the CALL/PUT badge clipping to “…”.",
      "You can now pin a hand-corrected trade so it survives settings rebuilds AND the in-browser Replay — the pinned result is kept as-is instead of being re-simulated. Fixed the Settings date-range picker getting clipped, and a stop above your entry (locked-in profit) no longer shows in the red loss colour.",
    ],
  },
  {
    v: "1.011", date: "2026-06-30",
    notes: [
      "Reworked the headline metric cards (dashboard + Trades page). Account return and Net P&L stay; the four trade metrics are now Trade win %, Avg win/loss, Profit factor and Trade expectancy — every number colour-coded green/red.",
      "Each trade metric has its own visual: Trade win % a win/loss donut; Avg win/loss the win-to-loss ratio with a green/red bar showing your average winner vs average loser in dollars; Profit factor (gross profit ÷ gross loss, above 1.0 = profitable) a green/red split bar; Trade expectancy (avg $ won/lost per trade) a green/red pulse line.",
      "Wording: the win-rate card now reads “5 wins · 4 losses” and Trade expectancy says “per trade”.",
      "Trade detail chart: the entry and exit dots now sit exactly on the price line — the line is anchored to the real fill prices, so the markers no longer float above or below the curve.",
      "P&L chart (% mode): the return now uses your account balance as the basis, so the chart’s total return matches the account-return card. Previously it summed each session’s return-on-capital, which inflated the figure (e.g. 17.9% vs the real 4.5%).",
      "Exit Lab: the per-strategy “avg return” column (which averaged each trade’s % and washed out to near zero) is replaced by “profit factor” — gross profit ÷ gross loss — a cleaner way to rank how each strategy’s exits actually perform.",
      "Exit handling is now a 3-way choice per strategy: Rules only · Rules + closes (new — your rules PLUS the trader’s full close, ignoring their partials/scales) · Follow trader. All strategies set to Rules + closes. The selector highlights the active mode in violet (the old on/off toggle was nearly invisible when on).",
    ],
  },
  {
    v: "1.010", date: "2026-06-29",
    notes: [
      "Settings → Machines: after a box command (Verify / Restart / etc.) finishes, the “done” note now clears itself after about a minute instead of lingering — it’s just a transient “last action” status.",
      "Settings layout: Dashboard + Streaming window sit side by side, and Alert sources + Broker accounts side by side, instead of stacked full-width — much less wide and empty on big screens (stacks back to one column on narrow ones). Paired cards line up to equal height.",
      "Trades page: fixed a stray “…” showing after the LOSS badge in the Result column — that column was too narrow and was clipping the badge.",
      "Strategies page: the cards now fill the full page width (and add columns on wide monitors) instead of staying a fixed width with empty space on the right.",
      "Settings page decluttered: Alert sources drops the long channel URL (it’s on hover now) and uses compact icon buttons; Machines shows one health dot (hover for Schwab/Discord/Supabase detail) with icon controls; helper text trimmed.",
    ],
  },
  {
    v: "1.009", date: "2026-06-26",
    notes: [
      "The dashboard and every page now use the full width of larger monitors instead of staying pinned to a fixed column with empty side margins. (It still caps on very wide ultrawide screens so tables don’t over-stretch.)",
      "The trade date is now its own DAY/MONTH column (Trades page + dashboard trades list) instead of being stacked above the time. It appears whenever there’s room — always on the wide Trades page, and on the dashboard list only when that panel is wide enough.",
      "Trades page table now fills the screen width with even, controlled column spacing — no more half-empty black area on wide monitors, and no big gaps between columns either. Long strategy names shorten with “…” (hover to read the full name).",
      "Secondary text — table headers, labels and captions — is brighter again on dark for easier reading.",
      "New “Activity” page: a live operational log streamed from every box — each session start/stop, and every entry/exit with its exact sizing basis (e.g. “×2 @ $1.78 — 60% day-budget”). You can finally see what each Mac did without opening it; filter by box. (Previously this only existed in a local file on whichever box was the leader.)",
      "Fix: when a second Mac ran the session, its trades could reuse low id numbers and overwrite older cloud data (it briefly stapled 4-day-old prices onto one of today’s trade charts). Each box now writes into its own id range, so two machines can never collide again.",
    ],
  },
  {
    v: "1.008", date: "2026-06-25",
    notes: [
      "Dashboard cards: “best trade” and “worst trade” are replaced by AVERAGE WIN % and AVERAGE LOSS % per trade — a clearer read on how the wins and losses actually size up.",
      "New first card: ACCOUNT RETURN % — your total P&L as a percentage of the account. For paper strategies it’s measured against a starting balance (set to $2,000); live strategies use the real Schwab balance. (Replaces the “open positions” card.)",
      "Trade chart shows just the trade again (entry → exit) by default, with a “full tape” toggle in the chart header to see the full recorded path (to ~30 min past close) when you want it.",
      "Fixed: the Trades page had gone blank — it was still wired to the old best/worst-trade cards. It now uses the new avg-win/avg-loss figures and loads again.",
      "Trades, the dashboard trade log and the Alerts feed now show a subtle DAY/MONTH divider line between days, so you can see which day each trade and alert belongs to.",
      "Closed trades show their stop level again (the final stop the trade rode) on both the dashboard and the Trades page.",
      "Removed the “on $2,000” line under Account return — it wasn’t useful.",
      "Full-tape chart: the entry/exit markers are kept in view so they always show, even on the longer recorded path.",
      "Account return is now a static, all-time figure (lifetime P&L ÷ starting balance) — it no longer moves when you change the date filter, since it’s a property of the account, not the window.",
      "Trades & trade log: dropped the day divider in favour of a regular date (DAY/MONTH) shown on each row, just above the time.",
      "Avg win and avg loss are shown in plain white now (no green/red).",
      "The Trades page uses the exact same six cards as the dashboard.",
      "Alerts page: added a Date column. The dashboard Alerts feed keeps its day divider, now with clearer spacing above each date.",
    ],
  },
  {
    v: "1.007", date: "2026-06-24",
    notes: [
      "Exit Lab fix: the per-strategy stats now ALWAYS cover all strategies (date filter only), as agreed — the strategy filter narrows only the Trades table above it. Yesterday's change had wrongly made the stats follow the strategy filter too.",
      "New strategy option “Manage exits by rules only”: the strategy still takes new ENTRY alerts but ignores the trader’s partial/close alerts — exits come purely from your own stop / breakeven / trailing / targets. Lets a strategy run its full plan.",
      "New per-strategy “Budget by weekday (%)”: trade a percentage of the budget on each weekday (Mon–Fri). e.g. Monday 50% on a $400 budget = $200/trade that day. 100% = full size.",
      "Fix: those two new options now stick. They were saving to the database fine, but the dashboard wasn't reading them back, so reopening the editor showed the old values. The editor now shows what you saved.",
      "Strategy cards are easier to read: each section (Sizing, Exits & risk, Sources) now has a clear header with an icon and a divider line, the settings are laid out in two columns instead of one long list, and default/“off” values are dimmed so your customised settings stand out.",
      "Replay fix: the “Recorded P&L” column now shows THIS strategy’s own result for each trade (e.g. Options live’s QQQ 724C = +$111, matching the trade detail) instead of accidentally borrowing another strategy’s number for the same alert.",
      "Replay fix: for a few older trades the replay was reading the WRONG price tape — old ID-clobbered ticks from a different day were stapled onto the trade, so a real winner (e.g. QQQ 724C, +$111) showed as a loss and the price chart never went green. Replay now uses each trade’s own clean session and picks the uncontaminated recording, so winners read as winners.",
      "New “Replay” on paper/draft strategy cards: re-run every recorded alert-trade this strategy would have taken (matched by its allowlist + sources, and sized to its budget) through its CURRENT settings — instantly, right in your browser. Works off the shared pool of recorded trades, so even a brand-new strategy with no trades of its own has something to replay. Shows replay vs recorded P&L and a per-trade list; click any trade for its replayed price chart and full action log. Saved separately, so your real trades are never touched. Strategies that follow the trader’s alerts replay those partial/close alerts too (a “rules only” strategy ignores them, exactly as it would live — so its replay can look worse than the recorded trades, which were closed by those alerts). (Runs the exact same engine the bot uses, so every setting — now and future — is reflected automatically.)",
    ],
  },
  {
    v: "1.006", date: "2026-06-23",
    notes: [
      "Machines: an offline/stale box now has a Remove button so you can clear a duplicate or a box you no longer use (it reappears on its own if it checks in again). Boxes also use a stable name now, so one Mac can’t show up twice.",
      "New safety alert: during the streaming window, if no box is actually trading, a red “Session at risk” banner appears at the top of every page — so a crashed, asleep, or offline box can never fail silently again.",
      "Recovered last week’s trades (the June 16 and June 18 wins) that had been dropped from the cloud, and fixed the underlying ID clash that caused them to be overwritten.",
      "The date filter now changes everything: Trades, the P&L chart and the stat cards all follow the selected range — not just the trades list. (Alerts always show the latest, regardless of range.)",
      "New “Default date range” in Settings → Dashboard, alongside Default view — pick the range the dashboard opens on.",
      "Exit Lab: the per-strategy stats now follow the same strategy filter as the trades above them, so the “left on table” numbers can’t disagree (e.g. 13.6% above vs 63% below).",
      "Per-trade P&L charts fixed: today’s trades were drawing a flat, week-wide line because of leftover samples from the ID clash — cleaned, so each chart now spans just its own trade.",
      "The trade log now shows the REAL trigger of every exit: rule-driven take-halves/targets show a ⚙️ with the reason (e.g. “+32% rule”), and alert-driven exits show a 🔔 with the actual alert (e.g. “Closed · LOCKED IN MAJORITY”) — so a rule no longer looks like an alert, and “Closed” no longer hides which alert caused it.",
      "A scale alert (“LOCKED IN MAJORITY”) no longer force-closes your runner — it takes half once to lock in profit, then lets the runner ride its stop (so a trailing strategy can actually trail).",
    ],
  },
  {
    v: "1.005", date: "2026-06-22",
    notes: [
      "New Machines panel in Settings — see each of your boxes at a glance: online/offline, which one is currently active (trading), when it was last seen, and its Schwab / Discord / Supabase connection health. Updates live.",
      "Groundwork for unattended daily auto-run with automatic failover across multiple boxes (most of it is bot-side); the dashboard now surfaces box status + re-auth reminders.",
      "“Connect a box” now matches how your Macs actually work: since the nitro-trader folder is in iCloud, it’s already on every Mac — so connecting one is just opening Documents → nitro-trader and double-clicking the installer. No download, no copying files. Each box keeps its own private login/data locally so they can’t clash.",
      "Settings page rebuilt to match the rest of the app: each section (Dashboard, Alert sources, Broker accounts, Machines) is now a full-width panel with its title inside the card and a proper table — no more everything squeezed into narrow cards on the right.",
      "Better contrast everywhere: secondary text, captions and table/card borders are lighter on dark (and darker on light) so labels and dividers are easier to read across all pages.",
      "Machines status is clearer: a box outside its trading window now reads “OFF-HOURS” (it auto-starts at the next session) instead of an alarming “OFFLINE”. A box only shows OFFLINE if it goes missing during a live session. You set up each Mac once — nothing is ever run daily.",
      "Streaming hours are now a real, editable setting (Settings → Streaming window): set when the trader streams — in US Eastern, with your local time shown beneath — plus how many minutes early the bot wakes. The top-bar Streaming row and the box “should it be running” logic both read it.",
      "The bot now runs on the streaming window, not the whole market day. It scans from your lead time before the start through the end, then keeps managing any still-open trades until they close (with a market-close safety net) and stops as soon as it’s flat — instead of idling until the 16:00 ET close every day.",
      "Exit behaviour: a “LOCKED IN MAJORITY”-style scale alert no longer force-closes your runner once you’ve already taken half — the runner now rides its stop (trailing / breakeven), so a trailing strategy can catch a bigger move. An explicit “closed” alert still closes fully.",
    ],
  },
  {
    v: "1.004", date: "2026-06-21",
    notes: [
      "Added a version number (bottom of the sidebar) and this Updates page, with the full history grouped by day.",
      "Strategies are now multiple cards, each linked to a live, paper or draft account — create, duplicate, delete, pick which sources it trades, and compare them side by side on the same alerts.",
      "New Settings page to manage alert channels and broker accounts; the Alerts page can filter by source.",
      "Top bar now shows a strategy summary (e.g. “1 live · 2 paper”) instead of a single-strategy picker.",
      "Dashboard and Trades share a strategy filter (top right, on-brand dropdown) — show all strategies, only the live ones, or a single one; set the default under Settings.",
      "Alerts feed: shows the real channel name and the action the bot took, a cleaner result, and clearer type colours — CLOSE and PARTIAL share a bright colour to stand out, ENTRY is calmer.",
      "Polish: strategy cards line up to equal height; native dropdowns restyled to match the app.",
      "Renamed Fronttesting → Exit Lab (and hid Backtesting for now); Alerts page gains a Source column; alert type colours softened (ENTRY/PARTIAL/CLOSE share a calmer amber, WATCH blue); strategy-card buttons aligned; Settings rebuilt into consistent Dashboard / Alert sources / Broker accounts sections.",
      "Renamed the “fronttest” account type to “Paper” everywhere (clearer now the page is Exit Lab); internal value unchanged.",
      "New strategy option “Stop to breakeven after first exit” (off = let the runner ride on its trailing/initial stop). The bot used to always do this; now it’s per-strategy — which is what lets a trailing strategy actually catch a runner.",
      "Strategy comparison moved to the Exit Lab: it now lists every trade across all strategies (with a strategy column + the shared strategy filter) and a per-strategy stats rollup below. The Strategies page is back to just the cards.",
      "Exit Lab: a date filter up top now scopes the whole page; the strategy filter moved into the Trades frame (its only consumer); the per-strategy stats always cover all strategies. “Realized %” counts partials (P&L ÷ cost basis).",
      "The date filter now remembers your choice across every page that uses it (like the strategy filter), and defaults to This week — a calendar week, Monday to Sunday.",
    ],
  },
  {
    v: "1.003", date: "2026-06-18",
    notes: [
      "Red “review needed” banner when the bot can’t tell which open trade an alert refers to.",
      "Alerts page now shows the Discord post-time and the delay until the order; moved the streaming dot onto the Alerts panel.",
      "Trade detail now shows the real recorded price path with entry / partial / exit markers, plus a “what happened” timeline (newest first).",
      "Hover the trade chart to read your % gain at any point along the line.",
      "Trade detail shows a loading placeholder instead of briefly flashing a fake chart.",
    ],
  },
  {
    v: "1.002", date: "2026-06-16",
    notes: [
      "Locked the dashboard to your Google account; login splash, plus sidebar name and sign-out.",
      "Strategies page: edit and save all strategy settings to the bot (budget, allowlist, stops, take-half, max-hold), with a warning before going live.",
      "Dashboard shows real data only — no demo numbers.",
      "Live mark-to-market P&L on open trades, and partial (½-sold) trades shown live.",
      "Instant realtime updates — pushed changes patch in place with no refresh.",
      "Trades table polish: stop column, tidier alignment, fills the card width evenly.",
      "Streaming dot blinks when live; alert feed and badge polish.",
      "Trailing-stop strategy option, including a tiered editor and a “give back N points of profit” model.",
      "Renamed “Dry-run” to “Simulation”, and made the ACTIVE toggle a real kill switch.",
      "On-brand confirm dialogs, fixed the modal close icon, and a Simulation/Live toggle.",
      "Strategies page: pause control, multi-card layout, take-profit, optional exits, and a dollar-based slippage cap.",
      "New Fronttesting page; each contract’s price is recorded for 30 min after it closes.",
    ],
  },
  {
    v: "1.001", date: "2026-06-15",
    notes: [
      "Launched the dashboard: live trades, alerts and P&L from the bot, behind a Google login.",
      "Polished the login screen with the Reezer logo.",
    ],
  },
];
